name: go vet test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  statictest:
    runs-on: ubuntu-latest
    container: golang:1.24
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install statictest
        run: |
          curl -L https://github.com/Yandex-Practicum/go-autotests/releases/download/v0.6.0/statictest-linux-amd64 -o statictest
          chmod +x statictest
          mv statictest /usr/local/bin/

      - name: Run statictest
        run: |
          go vet -vettool=$(which statictest) ./...