name: go vet test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  statictest:
    runs-on: ubuntu-latest
    container:
      image: golang:1.24
      options: --platform=linux/amd64  # Явно указываем архитектуру
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Go version
        run: |
          go version
          echo "GO_VERSION=$(go version | awk '{print $3}')" >> $GITHUB_ENV

      - name: Install statictest (AMD64)
        if: ${{ env.GO_VERSION == 'go1.24' }}
        run: |
          # Принудительно скачиваем версию для AMD64
          curl -L https://github.com/Yandex-Practicum/go-autotests/releases/download/v0.6.0/statictest-linux-amd64 -o statictest
          chmod +x statictest
          mv statictest /usr/local/bin/
          statictest -version

      - name: Update Go modules
        run: |
          go mod edit -go=1.24
          go mod tidy

      - name: Run vet
        run: |
          unset GOTOOLCHAIN
          go vet -vettool=$(which statictest) ./...
