name: go vet test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  statictest:
    runs-on: ubuntu-latest
    container: golang:1.21 # Исправлена версия Go
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect architecture
        run: echo "ARCH=$(uname -m)" >> $GITHUB_ENV

      - name: Install statictest
        run: |
          # Добавлена проверка доступности бинарников
          if [ "$ARCH" = "x86_64" ]; then
            URL="https://github.com/Yandex-Practicum/go-autotests/releases/download/v0.6.0/statictest-linux-amd64"
          elif [ "$ARCH" = "aarch64" ]; then
            URL="https://github.com/Yandex-Practicum/go-autotests/releases/download/v0.6.0/statictest-linux-arm64"
          else
            echo "Unsupported architecture: $ARCH"
            exit 1
          fi

          # Скачивание с проверкой кода ответа
          curl -L -o statictest "$URL" -f || (echo "Failed to download binary"; exit 1)
          
          # Проверка типа файла
          file statictest
          
          chmod +x statictest
          sudo mv statictest /usr/local/bin/

      - name: Verify binary
        run: |
          ldd /usr/local/bin/statictest || true
          /usr/local/bin/statictest -version

      - name: Run vet
        run: go vet -vettool=$(which statictest) ./...