name: go vet test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  statictest:
    runs-on: ubuntu-latest
    container: golang:1.24
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect architecture
        run: echo "ARCH=$(uname -m)" >> $GITHUB_ENV

      - name: Install statictest
        run: |
          # Скачиваем версию, соответствующую архитектуре
          if [ "$ARCH" = "x86_64" ]; then
            curl -L https://github.com/Yandex-Practicum/go-autotests/releases/download/v0.6.0/statictest-linux-amd64 -o statictest
          elif [ "$ARCH" = "aarch64" ]; then
            curl -L https://github.com/Yandex-Practicum/go-autotests/releases/download/v0.6.0/statictest-linux-arm64 -o statictest
          else
            echo "Unsupported architecture: $ARCH"
            exit 1
          fi

          chmod +x statictest
          mv statictest /usr/local/bin/

      - name: Verify binary
        run: |
          ldd /usr/local/bin/statictest || true
          /usr/local/bin/statictest -version

      - name: Run vet
        run: go vet -vettool=$(which statictest) ./...